AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for creating two S3 buckets

Parameters:
  SrcBucketName:
    Type: String
    Default: src-bkt-04-28
    Description: Name of the source S3 bucket

  DestBucketName:
    Type: String
    Default: dst-bkt-04-28
    Description: Name of the destination S3 bucket

  LambdaRuntimeVersion:
    Type: String
    Default: python3.12
    Description: Lambda runtime version to use.

Resources:
  SrcBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref SrcBucketName

  DestBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref DestBucketName

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntimeVersion
      Role: arn:aws:iam::194325853642:role/lambda-s3-access-role # IAM role that Lambda will use
      Handler: index.lambda_handler # Entry point: fileName.functionName
      Code:
        ZipFile: |
          import boto3
          import urllib.parse

          s3 = boto3.client('s3')

          def lambda_handler(event, context):
            source_bucket= event['Records'][0]['s3']['bucket']['name']
            source_key = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')

            destination_bucket = 'dst-bkt-04-28' 

            try:
              copy_source = {
                  'Bucket': source_bucket,
                  'Key': source_key
              }

              s3.copy(CopySource=copy_source, Bucket=destination_bucket, Key= source_key)
              print(f'Copied {source_bucket}/{source_key} to {destination_bucket}/{source_key}')

            except Exception as e:
                print(f'Error copying object: {e}')

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt SrcBucket.Arn

  S3NotificationCustomResourceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntimeVersion
      Role: arn:aws:iam::194325853642:role/lambda-s3-access-role
      Handler: index.handler
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          def handler(event, context):
              s3 = boto3.client('s3')
              props = event['ResourceProperties']
              try:
                  s3.put_bucket_notification_configuration(
                      Bucket=props['BucketName'],
                      NotificationConfiguration={
                          'LambdaFunctionConfigurations': [
                              {
                                  'LambdaFunctionArn': props['LambdaArn'],
                                  'Events': ['s3:ObjectCreated:*']
                              }
                          ]
                      }
                  )
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Message': str(e)})

  AttachLambdaToS3:
    Type: Custom::S3Notification
    DependsOn:
      - LambdaInvokePermission
    Properties:
      ServiceToken: !GetAtt S3NotificationCustomResourceLambda.Arn
      BucketName: !Ref SrcBucket
      LambdaArn: !GetAtt LambdaFunction.Arn
